# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true 이걸빼야 서버가 돌아감

# Setup
title:               Underbleu
tagline:             'bong&#39;s devlog'
description:        '봉봉이의 개발일지'
url:                 http://underbleu.github.io
baseurl:             ''
paginate:            8
plugins: [jekyll-paginate]
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

# About/contact
author:
  name:              bong Kim
  url:               https://underbleu.github.io
  email:             underbleu.dev@gmail.com
  github.repo:  https://github.com/underbleu

# Custom vars
version:             1.0.0


include: [_pages]

