# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true 이걸빼야 서버가 돌아감

# Setup
title:               Underbleu
tagline:             'bong devlog'
site.description:         'bong devlog'
url:                 http://underbleu.github.io
baseurl:             ''
paginate:            8
plugins: [jekyll-paginate]

# About/contact
author:
  name:              Bong Kim
  url:               https://underbleu.github.io
  email:             underbleu.dev@gmail.com
  github.repo:  https://github.com/underbleu

# Custom vars
version:             1.0.0


